apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJME1EY3hOVEV5TXpZMU9Wb1hEVE0wTURjeE5URXlNelkxT1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT1BZCnN4R3BTTVRxUmVUU2RJTGFDd2lVU2FhbWwxOTZLTVJuTG5jQmt0VUVvOHUvODROeHJ6alVGSWpiV0V2WWpWTFQKRlpaNkZwMENYZjE1b0ZLWUtnVkdwY2R3V2dSbzlFVWlXTXdmU1A0N0dnK3RBeGlUTDZuM1BVWGhtZjZLQWlYbAp6eHJuZlR2N2gxaUdJMkwzNHljTDgweDlROHNwTEpTN2txY2dhOFZoS04vK2cwdUFsSFlGczg3TzhjNXVoa256CkdONFBOOGQySUJoNndHY1JpU3JvaGZ3dVBXNkYzb2MwUDFMQXd0OXpoUzllc2tCcHgwd1YwQW9WcWJrY3FzNkcKZnZoZkxqYWZDSEMrNnNaSG9OczFQd3VzSmNULytlakI5N2FNNmtrWHNYUzVSSW9PQnA5bENuU3hoT2xFcGwzMwpCYnhhSCtwakh3bDF3RU5jaGhVQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJSDhMdUk2MkJnMVF3MDk1bzZ0ZDRzZ2VxNURNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDZVpEQmhaS3ZSYVhiYXlKZVU0cWVYeG5KNWY2RVdlUFdjaVhxTmh3NkxZVHVPcXdVdwpQdTJtTXBWOTloMkFSTW5kS0tCU2xvTHhiNXF6MktNSmozTkVhdG9vSXc4ODJzTkhDWVcwQmNzaVdHZFZ4czBzCjVtWEhad3pKb0J3L09ZMUFNVVhlOFIxK2xyNlhnODBxZE5HWUVDdEZFdGk0L0tPMzhzNWlHSkxReDc1RUNPWnAKK2I4dThKL3R0N21tNlBTakFkRCtKMXZOY2xubkdGYUo2Nk5qYmhyeXpoK0JnT0ptMVlnbCt2YWx4blhPYVhrbQpMMzYyOXZuWmlVY0VmSWt3MG9ZTC9RdW1ZVGcrTTA3MVlTNkZTTFRNR0Y2bk01Nmhrd3ZQcVJBVG1DdzdzeGowClkxbHMyZ1lDK1RLZXB5LzE5aHAyMmdBYlc0R2U5bm5lNGN6UQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://b140cf9e-18bc-4c4e-93cc-7f78a46231a1.api.k8s.fr-par.scw.cloud:6443
  name: k8s-vigilant-bhaskara
contexts:
- context:
    cluster: k8s-vigilant-bhaskara
    user: cli-config-00000000
  name: admin@k8s-vigilant-bhaskara
current-context: admin@k8s-vigilant-bhaskara
kind: Config
preferences: {}
users:
- name: cli-config-00000000
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
      - k8s
      - exec-credential
      command: scw
      installHint: |-
        This kubeconfig profile require scaleway-cli (scw) to authenticate.
        Installation instruction: https://github.com/scaleway/scaleway-cli#installation
      interactiveMode: Never

